name: Python CI

on:
  push:
    branches:
      - master  # Ejecuta el pipeline cuando haya cambios en la rama main
  pull_request:
    branches:
      - master  # También ejecuta el pipeline en pull requests hacia la rama main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Clonar el repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Versión de Python que estás usando

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Usa tu archivo requirements.txt

    # Paso 4: Ejecutar las pruebas
    - name: Run tests
      run: pytest test_gestor.py
